version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: saludya-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: saludya-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend